version: 2.1

orbs:
  openjdk: circleci/openjdk@17
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - openjdk/install:
          version: 17.0
      - run:
          name: Build and package Spring Boot application
          command: |
            ./mvnw clean package
            ./mvnw clean install

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - openjdk/install:
          version: 17.0
      - run:
          name: Run Spring Boot tests
          command: ./mvnw test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: shreeya42001/facilities-reservation
          tag: v1.0.1
      - docker/push:
          image: shreeya42001/facilities-reservation
          tag: v1.0.1

  deploy:
    docker:
      - image: shreeya42001/facilities-reservation:v1.0.1
